sudo: required
dist: trusty
language: python
git:
  depth: 10
  quiet: true
python:
  - "3.6"
env:
  matrix:
    - PROJECT="regal"
    - PROJECT="graph_matching_networks"
before_script:
  - sudo apt-get update -qq
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
script:
  - ./$PROJECT/run.sh

